Repository imaegoo/twikoo, pull requests merged in 2020-11, with the labels that each got.

#18 fix(deploy): 修复Win10字符编码导致的部署失败
  cloudbaserc.js
Labels: bug

#17 enable qiniu gravatar
  src/view/components/TkAvatar.vue
Labels: enhancement

#7 feat(admin): add admin panel
  cloudbaserc.js
  docs/.vuepress/config.js
  docs/README.md
  docs/configuration.md
  docs/faq.md
  docs/link.md
  docs/quick-start.md
  package.json
  public/demo.html
  src/function/README.md
  src/function/comment-get/index.js
  src/function/comment-get/package.json
  src/function/comment-like/index.js
  src/function/comment-like/package.json
  src/function/comment-submit/index.js
  src/function/comment-submit/package.json
  src/function/comment-submit/utils/mailer.js
  src/function/counter-get/index.js
  src/function/counter-get/package.json
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  src/js/main.js
  src/js/utils/api.js
  src/js/utils/index.js
  src/js/utils/timeago.js
  src/view/App.vue
  src/view/components/TkAdmin.vue
  src/view/components/TkAdminComment.vue
  src/view/components/TkAdminConfig.vue
  src/view/components/TkAdminImport.vue
  src/view/components/TkComment.vue
  src/view/components/TkComments.vue
  src/view/components/TkCounter.vue
  src/view/components/TkSubmit.vue
  src/view/index.js
Labels: enhancement

#24 fix(0.2.2): 修复问题
  docs/.vuepress/theme/layouts/Layout.vue
  docs/quick-start.md
  package.json
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  src/view/components/TkComment.vue
Labels: bug

#25 fix(0.2.3): 修复问题
  docs/.vuepress/theme/layouts/Layout.vue
  docs/faq.md
  docs/link.md
  docs/quick-start.md
  package.json
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  src/view/components/TkAdmin.vue
  src/view/components/TkAvatar.vue
Labels: bug

#30 fix(function): 修复新环境无法启用管理面板问题
  src/function/twikoo/index.js
Labels: bug

#32 fix(0.2.4): 修复问题
  docs/.vuepress/theme/layouts/Layout.vue
  docs/README.md
  docs/quick-start.md
  package.json
  src/function/twikoo/index.js
  src/view/components/TkMetaInput.vue
Labels: enhancement

#35 fix(0.2.5): 新增评论审核，修复问题
  README.md
  docs/.vuepress/theme/layouts/Layout.vue
  docs/README.md
  docs/quick-start.md
  docs/static/readme-1.png
  docs/static/readme-2.png
  package.json
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  src/view/components/TkAdminComment.vue
  src/view/components/TkAdminConfig.vue
  src/view/index.js
Labels: bug, enhancement
