Repository imaegoo/twikoo, pull requests merged in 2020-12, with the labels that each got.

#37 fix(0.2.6): 评论分页等
  docs/.vuepress/theme/layouts/Layout.vue
  docs/quick-start.md
  package.json
  src/function/twikoo/index.js
  src/view/App.vue
  src/view/components/TkAdminConfig.vue
  src/view/components/TkComment.vue
  src/view/components/TkComments.vue
Labels: enhancement

#39 fix(0.2.7): 优化评论管理布局，增加获取评论的API
  README.md
  docs/.vuepress/config.js
  docs/.vuepress/theme/layouts/Layout.vue
  docs/README.md
  docs/api.md
  docs/quick-start.md
  docs/static/readme-1.png
  docs/static/readme-2.png
  docs/static/readme-3.jpg
  package.json
  src/function/twikoo/index.js
  src/js/main.all.js
  src/js/main.js
  src/js/utils/index.js
  src/js/utils/timeago.js
  src/view/App.vue
  src/view/components/TkAdminComment.vue
  src/view/components/TkComment.vue
  src/view/components/TkComments.vue
  src/view/index.js
Labels: enhancement

#42 fix(0.2.8): 安全更新 样式更新 性能优化
  README.md
  docs/.vuepress/theme/layouts/Layout.vue
  docs/README.md
  docs/faq.md
  docs/quick-start.md
  package.json
  public/demo.css
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  src/view/App.vue
  src/view/components/TkAdmin.vue
  src/view/components/TkAdminConfig.vue
  src/view/components/TkAvatar.vue
  src/view/components/TkComment.vue
  src/view/components/TkMetaInput.vue
  src/view/components/TkSubmit.vue
Labels: bug

#43 feat(deploy): 支持一键部署
  .gitignore
  .npmignore
  cloudbaserc.js
  cloudbaserc.json
  docs/faq.md
  docs/quick-start.md
Labels: enhancement

#44 fix(0.2.9): 完善API 修复问题 新增评论导入
  README.md
  docs/.vuepress/config.js
  docs/.vuepress/theme/layouts/Layout.vue
  docs/README.md
  docs/api.md
  docs/quick-start.md
  docs/static/logo.png
  package.json
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  src/js/entites/comment.js
  src/js/main.all.js
  src/js/utils/index.js
  src/view/components/TkAdmin.vue
  src/view/components/TkAdminImport.vue
  src/view/components/TkComment.vue
Labels: bug, enhancement

#47 fix(0.3.0): 增加一些个性化配置
  docs/.vuepress/theme/layouts/Layout.vue
  docs/link.md
  docs/quick-start.md
  package.json
  src/function/twikoo/index.js
  src/view/components/TkAdminComment.vue
  src/view/components/TkAdminConfig.vue
  src/view/components/TkAvatar.vue
  src/view/components/TkComment.vue
  src/view/components/TkComments.vue
  src/view/components/TkSubmit.vue
Labels: enhancement

#51 fix(0.3.1): 头像获取优化，修复 bug
  .editorconfig
  .eslintignore
  .eslintrc.js
  README.md
  docs/.vuepress/theme/layouts/Layout.vue
  docs/README.md
  docs/quick-start.md
  package.json
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  src/js/entites/comment.js
  src/js/utils/avatar.js
  src/js/utils/index.js
  src/view/App.vue
  src/view/components/TkAdminComment.vue
  src/view/components/TkAdminConfig.vue
  src/view/components/TkAvatar.vue
  src/view/components/TkComment.vue
  src/view/components/TkCounter.vue
  src/view/components/TkFooter.vue
  src/view/components/TkMetaInput.vue
  src/view/components/TkSubmit.vue
  webpack.config.js
Labels: bug, enhancement

#55 fix(0.3.2): 修复 API 头像问题
  docs/.vuepress/theme/layouts/Layout.vue
  docs/README.md
  docs/faq.md
  docs/quick-start.md
  package.json
  src/function/twikoo/index.js
  src/js/utils/index.js
  src/view/components/TkComment.vue
Labels: bug

#58 fix(0.3.3): 修复问题
  docs/.vuepress/theme/layouts/Layout.vue
  docs/quick-start.md
  package.json
  src/function/twikoo/index.js
  src/view/components/TkAdminComment.vue
  src/view/components/TkComments.vue
  src/view/components/TkPagination.vue
  src/view/index.js
Labels: bug

#59 WIP: feat(0.4.0): 功能更新
  .eslintignore
  README.md
  docs/.vuepress/config.js
  docs/.vuepress/theme/layouts/Layout.vue
  docs/README.md
  docs/cms.md
  docs/quick-start.md
  package.json
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  src/view/App.vue
  src/view/components/TkAdmin.vue
  src/view/components/TkAdminConfig.vue
  src/view/components/TkSubmit.vue
  src/view/index.js
  src/view/lib/owo.css
  src/view/lib/owo.js
  webpack.config.js
Labels: enhancement

#65 fix(0.4.1): 修复问题
  .npmignore
  docs/.vuepress/theme/layouts/Layout.vue
  docs/quick-start.md
  package.json
  src/function/twikoo/index.js
  src/view/App.vue
  src/view/components/TkAdmin.vue
  src/view/components/TkAdminComment.vue
  src/view/components/TkAdminConfig.vue
  src/view/components/TkComment.vue
  src/view/components/TkMetaInput.vue
  src/view/components/TkPagination.vue
  src/view/components/TkSubmit.vue
  src/view/lib/owo.css
Labels: bug, enhancement

#67 feat(0.4.2): 功能更新
  docs/.vuepress/theme/layouts/Layout.vue
  docs/README.md
  docs/faq.md
  docs/quick-start.md
  docs/static/katex.png
  package.json
  public/demo.html
  src/function/twikoo/index.js
  src/js/tcb/index.js
  src/js/utils/index.js
  src/js/utils/marked.js
  src/view/components/TkAdminComment.vue
  src/view/components/TkAdminConfig.vue
  src/view/components/TkComment.vue
  src/view/components/TkSubmit.vue
Labels: enhancement

#73 doc(quick): update doc
  docs/quick-start.md
Labels: documentation

#75 fix(0.4.4)
  docs/.vuepress/theme/layouts/Layout.vue
  docs/quick-start.md
  package.json
  public/demo.html
  src/function/twikoo/index.js
  src/js/entites/config.js
  src/js/utils/api.js
  src/view/App.vue
  src/view/components/TkAdminConfig.vue
  src/view/components/TkComment.vue
  src/view/components/TkComments.vue
  src/view/components/TkFooter.vue
  src/view/components/TkMetaInput.vue
  src/view/components/TkSubmit.vue
  src/view/lib/owo.css
Labels: bug, enhancement

#76 fix(0.4.5)
  src/view/components/TkSubmit.vue
Labels: bug

#78 docs(0.4.5)
  README.md
  docs/README.md
Labels: documentation

#79 fix(deploy): 修复一键部署
  cloudbaserc.json
  src/function/twikoo/index.js
Labels: bug

#83 feat(0.5.0): 代码高亮
  README.md
  docs/.vuepress/theme/layouts/Layout.vue
  docs/README.md
  docs/faq.md
  docs/quick-start.md
  package.json
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  src/js/entites/config.js
  src/js/utils/highlight.js
  src/js/utils/index.js
  src/view/components/TkAdminComment.vue
  src/view/components/TkAdminConfig.vue
  src/view/components/TkAvatar.vue
  src/view/components/TkComment.vue
  src/view/components/TkComments.vue
  src/view/components/TkSubmit.vue
Labels: documentation, enhancement

#85 docs(api): 补充文档遗漏的地域参数
  docs/api.md
  docs/quick-start.md
Labels: documentation
