Repository imaegoo/twikoo, pull requests merged in 2021-01, with the labels that each got.

#86 fix(0.5.1): 修复导入功能
  .npmignore
  babel.config.json
  demo/demo.css
  demo/demo.html
  demo/index.html
  docs/.vuepress/theme/layouts/Layout.vue
  docs/quick-start.md
  package.json
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  webpack.config.js
Labels: bug

#91 chore(ci): fix docs build action
  .github/workflows/docs.yml
  package.json
Labels: dependencies

#94 modify zh-tw zh-hk
  src/js/utils/i18n/zh-HK.json
  src/js/utils/i18n/zh-TW.json
Labels: enhancement

#92 fix(0.5.2): 修复控制台报错 支持多语言
  README.md
  cloudbaserc.json
  demo/demo.html
  docs/.vuepress/theme/layouts/Layout.vue
  docs/README.md
  docs/api.md
  docs/quick-start.md
  package.json
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  src/js/utils/highlight.js
  src/js/utils/i18n/index.js
  src/js/utils/i18n/zh-CN.json
  src/js/utils/i18n/zh-HK.json
  src/js/utils/i18n/zh-TW.json
  src/js/utils/index.js
  src/js/utils/timeago.js
  src/view/components/TkAdmin.vue
  src/view/components/TkAdminComment.vue
  src/view/components/TkAdminConfig.vue
  src/view/components/TkAdminImport.vue
  src/view/components/TkAvatar.vue
  src/view/components/TkComment.vue
  src/view/components/TkComments.vue
  src/view/components/TkMetaInput.vue
  src/view/components/TkPagination.vue
  src/view/components/TkSubmit.vue
Labels: bug

#97 chore(0.6.0): 简化云函数部署方式
  .github/workflows/publish.yml
  demo/demo.html
  docs/.vuepress/config.js
  docs/.vuepress/theme/layouts/Layout.vue
  docs/README.md
  docs/cms.md
  docs/faq.md
  docs/link.md
  docs/quick-start.md
  docs/static/readme-1.png
  docs/static/readme-2.png
  docs/static/readme-3.jpg
  package.json
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  src/view/components/TkComments.vue
Labels: enhancement

#99 fix(ci): 修复 npm publish 失败
  .github/workflows/publish.yml
Labels: bug

#113 feat(1.1.0-beta): 功能更新
  .eslintignore
  .github/workflows/publish.yml
  README.md
  demo/demo.html
  docs/.vuepress/theme/layouts/Layout.vue
  docs/README.md
  docs/quick-start.md
  package.json
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  src/js/entites/comment.js
  src/js/utils/emotion.js
  src/js/utils/i18n/zh-CN.json
  src/js/utils/i18n/zh-HK.json
  src/js/utils/i18n/zh-TW.json
  src/js/utils/index.js
  src/js/utils/marked.js
  src/lib/marked/Lexer.js
  src/lib/marked/Parser.js
  src/lib/marked/README.md
  src/lib/marked/Renderer.js
  src/lib/marked/Slugger.js
  src/lib/marked/TextRenderer.js
  src/lib/marked/Tokenizer.js
  src/lib/marked/defaults.js
  src/lib/marked/helpers.js
  src/lib/marked/marked.js
  src/lib/marked/rules.js
  src/lib/owo.css
  src/lib/owo.js
  src/view/App.vue
  src/view/components/TkAdmin.vue
  src/view/components/TkAdminComment.vue
  src/view/components/TkComment.vue
  src/view/components/TkComments.vue
  src/view/components/TkMetaInput.vue
  src/view/components/TkSubmit.vue
  src/view/index.js
Labels: enhancement

#115 fix(emotion): 修复颜文字插入为缩写的问题
  docs/.vuepress/theme/layouts/Layout.vue
  package.json
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  src/lib/owo.js
  src/view/App.vue
Labels: bug

#120 fix(secure): 修复 style 注入问题，修复邮箱地址大小写问题，修复 AKISMET_KEY 不生效
  README.md
  docs/.vuepress/theme/layouts/Layout.vue
  docs/README.md
  package.json
  src/function/twikoo/index.js
  src/function/twikoo/package.json
  src/js/utils/avatar.js
  src/view/components/TkMetaInput.vue
Labels: bug

#128 doc(quick-start): 更新快速上手文档
  docs/quick-start.md
Labels: documentation
